---
- name: Remove CTngexp Folder from All Relevant Hosts
  hosts: CA, Logger, Monitor  # This will target all the CA, Logger, and Monitor hosts
  tasks:
    - name: Remove CTngexp folder from /tmp
      ansible.builtin.file:
        path: /tmp/CTngexp
        state: absent  # This will remove the folder and its contents
