---
- hosts: CA, Logger, Monitor,Control  # This will target all the CA, Logger, Monitor, and Control hosts
  tasks:
    - name: Update Go module
      ansible.builtin.command:
        cmd: /tmp/go/bin/go get github.com/jik18001/CTngV2@latest
        chdir: /tmp/CTngexp

    - name: Run go mod tidy
      ansible.builtin.command:
        cmd: /tmp/go/bin/go mod tidy
        chdir: /tmp/CTngexp

    - name: Build the project
      ansible.builtin.command:
        cmd: /tmp/go/bin/go build .
        chdir: /tmp/CTngexp
